package com.africa.semicolon.evoting.enums;


public enum ElectionType {

    PRESIDENTIAL_ELECTION, SENATORIAL_ELECTION,
    FEDERAL_HOUSE_OF_REPRESENTATIVE_ELECTION,
    GUBERNATORIAL_ELECTION, STATE_HOUSE_OF_REPRESENTATIVE_ELECTION,
    LOCAL_GOVERNMENT_CHAIRMANSHIP_ELECTION, WARD_COUNCILLOR_ELECTION;


}
